<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\Habitat.BackEnd.Progress.Application\Habitat.BackEnd.Progress.Application.csproj" />
    <ProjectReference Include="..\..\src\Habitat.BackEnd.Progress.Infrastructure\Habitat.BackEnd.Progress.Infrastructure.csproj" />
  </ItemGroup>
</Project>
